version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: incassator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11lr00
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://postgres:11lr00@db:5432/incassator_db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python init_db.py && python -c 'from generator import generate_atms; from data_loader import save_atms; save_atms(generate_atms(1000))' && gunicorn --bind 0.0.0.0:5000 app:app"

volumes:
  pgdata:
