name: Python CI
on:
  push:
    branches: [ "main", "develop", "deploy" ]
  pull_request:
    branches: [ "main", "develop", "deploy" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install pytest numpy scikit-learn psycopg2-binary osmnx networkx
    - name: Run tests
      run: |
        python -m pytest tests/
      env:
        PYTHONPATH: ${{ github.workspace }}
        
